# fly.toml app configuration file generated for argamag on 2026-05-26T18:29:31-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'argamag'
primary_region = 'nrt'

[build]

[env]
  CORS_ORIGINS = 'https://argamag.fly.dev'
  DB_PATH = '/data/horse.db'
  UPLOADS_DIR = '/data/uploads'

[[mounts]]
  source = 'argamag_data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 150

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
